/**
 * Turns every single-file widget bundle in dist-ui/ into a TypeScript string
 * constant under src/generated/, so the server ships the HTML inside its own
 * module graph instead of resolving a file path at runtime.
 *
 * Run via `pnpm run gen:ui` (after `vite build --config vite.ui.config.ts`).
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const distUi = fileURLToPath(new URL('../dist-ui', import.meta.url));
const outDir = fileURLToPath(new URL('../src/generated', import.meta.url));

const constantName = (widget) => `${widget.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}_HTML`;

let widgets;
try {
  widgets = readdirSync(distUi, { withFileTypes: true }).filter((entry) => entry.isDirectory());
} catch (error) {
  throw new Error(`Cannot read ${distUi} — run the vite widget build first`, { cause: error });
}

if (widgets.length === 0) {
  throw new Error(`No widget bundles in ${distUi} — the vite build produced nothing`);
}

mkdirSync(outDir, { recursive: true });

for (const widget of widgets) {
  const html = readFileSync(join(distUi, widget.name, 'index.html'), 'utf8');
  const target = join(outDir, `${widget.name}-html.ts`);

  writeFileSync(
    target,
    [
      '// GENERATED by pnpm gen:ui — do not edit',
      `export const ${constantName(widget.name)}: string = ${JSON.stringify(html)};`,
      '',
    ].join('\n'),
  );

  console.log(`gen:ui → src/generated/${widget.name}-html.ts (${html.length} chars)`);
}
