/**
 * Turns every single-file widget bundle in dist-ui/ into a TypeScript string
 * constant under src/generated/, so the server ships the HTML inside its own
 * module graph instead of resolving a file path at runtime.
 *
 * Run via `pnpm run gen:ui` (after `vite build --config vite.ui.config.ts`).
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const uiRoot = fileURLToPath(new URL('../ui', import.meta.url));
const distUi = fileURLToPath(new URL('../dist-ui', import.meta.url));
const outDir = fileURLToPath(new URL('../src/generated', import.meta.url));

const constantName = (widget) => `${widget.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}_HTML`;

// The widget list comes from the sources, using the same rule as the vite
// config — not from whatever directories the build happened to leave in
// dist-ui. That keeps emitted asset folders out of the list and turns a widget
// that silently failed to build into a named error instead of a missing export.
const widgets = readdirSync(uiRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && existsSync(join(uiRoot, entry.name, 'index.html')))
  .map((entry) => entry.name);

if (widgets.length === 0) {
  throw new Error(`No widgets found — expected at least one ${uiRoot}/<widget>/index.html`);
}

mkdirSync(outDir, { recursive: true });

for (const widget of widgets) {
  const bundle = join(distUi, widget, 'index.html');

  if (!existsSync(bundle)) {
    throw new Error(
      `Widget "${widget}" has no bundle at ${bundle} — run the vite widget build first`,
    );
  }

  const html = readFileSync(bundle, 'utf8');

  writeFileSync(
    join(outDir, `${widget}-html.ts`),
    [
      '// GENERATED by pnpm gen:ui — do not edit',
      `export const ${constantName(widget)}: string = ${JSON.stringify(html)};`,
      '',
    ].join('\n'),
  );

  console.log(`gen:ui → src/generated/${widget}-html.ts (${html.length} chars)`);
}
