/**
 * Builds every widget under ui/ into a single-file bundle and turns each into a
 * TypeScript string constant under src/generated/, so the server ships the HTML
 * inside its own module graph instead of resolving a file path at runtime.
 *
 * One Vite pass per widget, deliberately: a single pass over several entries
 * makes Rollup split out everything they share, and nothing inlines those
 * chunks back in — see the comment in vite.ui.config.ts.
 *
 * Run via `pnpm run gen:ui`.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'vite';

const uiRoot = fileURLToPath(new URL('../ui', import.meta.url));
const distUi = fileURLToPath(new URL('../dist-ui', import.meta.url));
const outDir = fileURLToPath(new URL('../src/generated', import.meta.url));
const configFile = fileURLToPath(new URL('../vite.ui.config.ts', import.meta.url));

const constantName = (widget) => `${widget.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}_HTML`;

// The widget list comes from the sources, using the same rule as the vite
// config — not from whatever directories the build happened to leave in
// dist-ui. That keeps emitted asset folders out of the list and turns a widget
// that silently failed to build into a named error instead of a missing export.
const widgets = readdirSync(uiRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && existsSync(join(uiRoot, entry.name, 'index.html')))
  .map((entry) => entry.name);

if (widgets.length === 0) {
  throw new Error(`No widgets found — expected at least one ${uiRoot}/<widget>/index.html`);
}

mkdirSync(outDir, { recursive: true });
rmSync(distUi, { recursive: true, force: true });

for (const widget of widgets) {
  process.env.RIS_UI_WIDGET = widget;
  await build({ configFile, mode: 'production', logLevel: 'warn' });

  const bundle = join(distUi, widget, 'index.html');

  if (!existsSync(bundle)) {
    throw new Error(
      `Widget "${widget}" has no bundle at ${bundle} — run the vite widget build first`,
    );
  }

  const html = readFileSync(bundle, 'utf8');

  // A leftover cross-chunk reference means the bundle is not self-contained:
  // the file it names is never written, so the widget would fail to start in
  // every host while still passing every "no external URL" check. Static and
  // dynamic both — ext-apps reaches for zod's JSON-Schema converter through
  // `import("…")`, which `inlineDynamicImports` in vite.ui.config.ts is what
  // resolves. There is deliberately no allowlist: a reference that survives
  // here is one nothing can load at runtime.
  const dangling = /\b(?:from|import)\s*\(?\s*["']\.[^"']*["']/.exec(html);
  if (dangling) {
    throw new Error(`Widget "${widget}" was not fully inlined — it still imports ${dangling[0]}`);
  }

  writeFileSync(
    join(outDir, `${widget}-html.ts`),
    [
      '// GENERATED by pnpm gen:ui — do not edit',
      `export const ${constantName(widget)}: string = ${JSON.stringify(html)};`,
      '',
    ].join('\n'),
  );

  console.log(`gen:ui → src/generated/${widget}-html.ts (${html.length} chars)`);
}
